In [1]:
%tensorflow_version 1.x
import pickle
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '1'  # or any {'0', '1', '2'}
import tensorflow as tf
import keras
import pandas as pd
import numpy as np
import nltk
import spacy
from nltk.corpus import stopwords
from tqdm import tqdm
nltk.download('stopwords')
nlp = spacy.load('en', disable=['parser', 'ner'])

TensorFlow 1.x selected.


Using TensorFlow backend.


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
pickle_in = open("elmo_train_final1.pickle","rb")
elmo_train_new = pickle.load(pickle_in)

In [ ]:
elmo_train_new.shape[1]

1024

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
dataset = pd.read_csv("ISEAR.csv")

In [ ]:
Y = dataset.iloc[:,0].values

In [ ]:
Y

In [ ]:
len(Y)

7515

In [ ]:
classifier4 = Sequential()

In [ ]:
classifier4.add(Dense(output_dim = 512,init = 'uniform',activation = 'relu',input_dim = 1024))
classifier4.add(Dense(output_dim = 512,init = 'uniform',activation = 'relu'))
classifier4.add(Dense(output_dim = 8,init = 'uniform',activation='softmax'))
classifier4.compile('adam', 'categorical_crossentropy', metrics=['accuracy'])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=1024, units=512, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=512, kernel_initializer="uniform")`
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=8, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
#from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(elmo_train_new, Ycat, test_size = 0.20, random_state = 42)

In [ ]:
classifier4.fit(elmo_train_new,Ycat,batch_size = 10,epochs=100)

Epoch 1/100
7515/7515 [==============================] - 8s 1ms/step - loss: 1.6105 - accuracy: 0.3742
Epoch 2/100
7515/7515 [==============================] - 8s 1ms/step - loss: 1.3413 - accuracy: 0.4959
Epoch 3/100
7515/7515 [==============================] - 8s 1ms/step - loss: 1.2234 - accuracy: 0.5405
Epoch 4/100
7515/7515 [==============================] - 8s 1ms/step - loss: 1.1477 - accuracy: 0.5776
Epoch 5/100
7515/7515 [==============================] - 8s 1ms/step - loss: 1.0894 - accuracy: 0.5968
Epoch 6/100
7515/7515 [==============================] - 8s 1ms/step - loss: 1.0150 - accuracy: 0.6283
Epoch 7/100
7515/7515 [==============================] - 8s 1ms/step - loss: 0.9452 - accuracy: 0.6559
Epoch 8/100
7515/7515 [==============================] - 8s 1ms/step - loss: 0.8843 - accuracy: 0.6814
Epoch 9/100
7515/7515 [==============================] - 8s 1ms/step - loss: 0.8393 - accuracy: 0.6966
Epoch 10/100
7515/7515 [==============================] - 8s 1ms/step - l

In [ ]:
Y[0:10]

array([1, 2, 3, 4, 5, 7, 6, 1, 2, 3], dtype=object)

In [ ]:
for i in range(0,len(Y)):
  if Y[i] == 'fear':
    Y[i] = 1
  elif Y[i] == 'anger':
    Y[i] = 2
  elif Y[i] == 'sadness':
    Y[i] = 3
  elif Y[i] == 'disgust':
    Y[i] = 4
  elif Y[i] == 'shame':
    Y[i] = 5
  elif Y[i] == 'joy':
    Y[i] = 6
  else :
    Y[i] = 7

In [ ]:
for i in ypred_back:
  if i not in range(1,8):
    print(i)

In [ ]:
from keras.utils import to_categorical
Ycat = to_categorical(Y)

In [ ]:
Y

array([1, 2, 3, ..., 1, 7, 1], dtype=object)

In [ ]:
Ycat

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
Ycat.shape[0],Ycat.shape[1]

(7515, 8)

In [ ]:
ypred = classifier4.predict(X_test)

In [ ]:
ypred_back1 =[]

In [ ]:
ypred_back1

In [ ]:
for i in range(0,len(ypred_back)):
  if(ypred_back[i] in emotion_map):
    ypred_back1.append(emotion_map.get(ypred_back[i]))

In [ ]:
ytest_back

array([4, 5, 1, ..., 4, 2, 2])

In [ ]:
ypred_back = np.argmax(ypred,axis = -1)

In [ ]:
ytest_back = np.argmax(y_test,axis = -1)

In [ ]:
accuracy_score(ytest_back, ypred_back)

In [ ]:
model_json = classifier4.to_json()
with open("model2.json","w") as jsonfile:
  jsonfile.write(model_json)

In [ ]:
classifier4.save_weights("weights2.h5")

In [ ]:
emotion_map = {}

In [ ]:
emotion_map ={1:'fear',2:'anger',3:'sadness',4:'disgust',5:'shame',6:'joy',7:'guilt'}

In [ ]:
import nltk
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [2]:
from keras.models import model_from_json
json_file = open('model2.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
classifier4 = model_from_json(loaded_model_json)
classifier4.load_weights('weights2.h5')

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [3]:
import tensorflow_hub as hub
elmo = hub.Module("https://tfhub.dev/google/elmo/2", trainable=True)

In [4]:
def elmo_vectors(x):
  embeddings = elmo(x, signature="default", as_dict=True)["elmo"]

  with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(tf.tables_initializer())
    # return average of ELMo features
    return sess.run(tf.reduce_mean(embeddings,1))

In [5]:
from nltk.corpus import stopwords
negation_words = ['no','not', 'neither', 'nor', 'but', 'however', 'although', 'nonetheless', 'despite', 'except', 'even though', 'yet']
stop_words = stopwords.words('english')
for word in stop_words:
  if word in negation_words:
    stop_words.remove(word)
stop_words = set(stop_words)

In [6]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [7]:
tf.get_logger().setLevel('INFO')

In [8]:
emotion_map ={1:'fear',2:'anger',3:'sadness',4:'disgust',5:'shame',6:'joy',7:'guilt'}

In [9]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [10]:
from nltk.stem import WordNetLemmatizer
wnl = WordNetLemmatizer()


In [11]:
import json
file = open('canswers.json')
na = json.load(file)
file1 = open('cqa.json')
ds = json.load(file1)


In [12]:
ans = [ds[key] for id,key in enumerate(ds)]
ds1 = {}
for id,key in enumerate(ds):
  ds1[key] = ds[key].lower()

In [13]:
tf.logging.set_verbosity(tf.logging.ERROR) 

In [14]:
import gensim
from gensim.utils import simple_preprocess
from gensim.parsing.preprocessing import STOPWORDS
from nltk.stem import WordNetLemmatizer, SnowballStemmer
from nltk.stem.porter import *
stemmer = SnowballStemmer("english")
def lemmatize_stemming(text):
    return stemmer.stem(WordNetLemmatizer().lemmatize(text, pos='v'))

negation_words = ['not', 'neither', 'nor', 'but', 'however', 'although', 'nonetheless', 'despite', 'except', 'even though', 'yet']
# Tokenize and lemmatize
def preprocess(text):
    text = re.sub('[^a-zA-Z]',' ',text)
    text = text.lower()
    text = re.sub("\?"," ?",text)
    words = [word for word in STOPWORDS if word not in negation_words]
    result=[]
    for token in gensim.utils.simple_preprocess(text) :
        if len(token) >= 3 and token not in words:
            result.append(lemmatize_stemming(token))
            
    return result

In [15]:
negation_words = ['not', 'neither', 'nor', 'but', 'however', 'although', 'nonetheless', 'despite', 'except', 'even though', 'yet']
stop_words = stopwords.words('english')
for word in stop_words:
  if word in negation_words:
    stop_words.remove(word)
def preproc1(text):
  punctuation = '!"#$%&()*+-/:;<=>?@[\\]^_`{|}~'
  text = text.split()
  text = ' '.join(word for word in text if word not in stop_words)
  text = ''.join(word for word in text if word not in set(punctuation))
  text = text.lower()
  text = text.replace('[0-9]',' ')
  text = ' '.join(text.split())
  output = []
  s = [token.lemma_ for token in nlp(text)]
  output.append(' '.join(s))
  return output

In [ ]:
preproc('Every time I imagine that someone I love or I could contact a serious illness, even death.')

['everi', 'time', 'imagin', 'that', 'someon', 'love', 'could', 'contact', 'serious', 'ill', 'even', 'death']


'fear'

In [16]:
def preproc(line):
  line = re.sub('  \n',' ',line)
  newline = line
  nl1 = line
  #print(newline)
  if newline[-1] == '?' or line[0] in wh_questions:
    if line[0] in wh_questions:
      line.remove(line[0])
    max_count = 0
    max_count1 = 0
    ans = ""
    ans1 = ""
    for idx,key in enumerate(ds1):
      l = key.split()
      count = 0
      for i in range(0,len(line)):
          if line[i] in l:
            count = count+1
      if count > max_count:
        max_count = count
        ans = ds[key]
    for idx,key in enumerate(na):
      l = key.split()
      c1 = 0
      for i in range(0,len(line)):
          if line[i] in l:
            c1 = c1+1
      if c1 > max_count1:
        max_count1 = c1
        ans1 = na[key]
    if max_count1 > max_count:
      ans = ans1
    if ans == "":
      ans = "Hmm.. I need to think about it."
    print(ans)
    return -100
  line = preprocess(line)
  print(line)
  new_train = elmo_vectors(line)
  pred = classifier4.predict(new_train)
  #print(pred)
  pred1 = np.argmax(pred,axis = -1)
  if pred[0][pred1[0]] != 1:
    return "neutral"
  return emotion_map.get(pred1[0])

In [17]:
affirm_ans = ["Thats great to hear!","Wow that sounds fun!","I really like it too!","I am proud of you :)","Lucky you!","Thank you for telling me this!","I am so lucky to chat with you!","Wow!!"]
neg_ans = ["It do be like that sometimes.","Poor you :(","Wish I could hug you right now..","Aww hope you feel better soon","You always have me to talk too :)","It will pass soon!","I hope you get better soon.."]
compliments = ["You are awesome :)","I love spending time with you :)","Wish I could see you right now!","You are perfect!","Never change! You are awesome :)","Sending virtual hugs and kisses :)","You are my best friend!","I love you :)"]


In [18]:
def aggregate():
  num_emotions = []
  for i in range(0,len(last_6_emotions)):
    num_emotions.append(new_emotion_map.get(last_6_emotions[i]))
  swing_vector = []
  for i in range(0,len(last_6_emotions)-1):
    swing_vector.append(swings[num_emotions[i]][num_emotions[i+1]])
  #print(swing_vector)
  max_swing = []
  max_swing.append(np.argmax(swing_vector))
  for i in range(0,len(swing_vector)):
    if i != max_swing[0]:
      if swing_vector[i] == swing_vector[max_swing[0]]:
        max_swing.append(i)
  #print(max_swing)
  replace_index = -1
  if len(max_swing) > 1:
    for i in range(0,len(max_swing)-1):
      if max_swing[i] + 1 == max_swing[i+1]:
        replace_index = max_swing[i+1]
        break
  if replace_index == -1:
    replace_index = max_swing[0]
  #print(replace_index)
  new_swing = swing_vector
  #new_swing.insert(0,0)
  #new_swing.insert(len(new_swing),0)
  #print(new_swing)
  i = replace_index
  if replace_index != 0 and replace_index != len(swing_vector)-1:
    diff = (abs(swing_vector[i+1]-swing_vector[i]) - abs(swing_vector[i]-swing_vector[i-1]))
    if diff > 0 :
      replace_emotion = i + 1
    else:
      replace_emotion = i
  else :
    replace_emotion = i
  #print(replace_emotion)
  num_emotions.pop(replace_emotion)
  sum_weights = 0
  for el in num_emotions:
    sum_weights = sum_weights + el
  total_emotion = sum_weights/len(num_emotions)
  tot = (total_emotion/8.0) * 10
  #print(total_emotion,tot)
  return tot

In [19]:
wh_questions = ["who","when","how","where","why","which","what"]

In [20]:
new_emotion_map = {'joy':1,'neutral':2,'disgust':3,'anger':4,'guilt':5,'shame':6,'fear':7,'sadness':8}

In [21]:
swings = [[],[0,0,0,4,4,4,4,4,5],[0,0,0,0,0,0,0,0,0],[0,4,0,0,0,2,2,2,3],[0,4,0,0,0,2,2,2,3],[0,4,0,2,2,0,0,0,1],[0,4,0,2,2,0,0,0,1],[0,4,0,2,2,0,0,0,1],[0,5,0,3,3,2,2,2,0]]

In [22]:
def get_emotion_details(emotion):
  
    if len(df) == 0:
      df.append(emotion)
      return 0
    latest_emotion = df[-1]
    diff = emotion - latest_emotion
    if diff > 0:
      percentage = diff/emotion * 100
      percentage = -percentage
    else :
      percentage = abs(diff)/latest_emotion * 100
    df.append(emotion)
    return percentage

In [23]:
from IPython.display import HTML, display

def set_css():
  display(HTML('''
  <style>
    pre {
        white-space: pre-wrap;
    }
  </style>
  '''))
get_ipython().events.register('pre_run_cell', set_css)

In [58]:
with open('familywords.txt','r') as fpfam:
  familywords = fpfam.read().split(', ')
for i,word in enumerate(familywords):
  familywords[i] = preprocess(word)
familywords = [j for sub in familywords for j in sub]
familywords = list(set(familywords))
with open('schoolwords.txt','r') as fpschool:
  schoolwords = fpschool.read().split(', ')
for i,word in enumerate(schoolwords):
  schoolwords[i] = preprocess(word)
schoolwords = [j for sub in schoolwords for j in sub]
schoolwords = list(set(schoolwords))
with open('verb.txt','r') as fpverb:
  verbwords = fpverb.read().split(', ')
for i,word in enumerate(verbwords):
  verbwords[i] = preprocess(word)
verbwords = [j for sub in verbwords for j in sub]
verbwords = list(set(verbwords))
with open('posfeelings.txt') as fppos:
  posfwords = fppos.read().split(', ')
  for i, word in enumerate(posfwords):
    posfwords[i] = preprocess(word)
posfwords = [j for sub in posfwords for j in sub]
posfwords = list(set(posfwords))
with open('negfeelings.txt') as fpneg:
  negfwords = fpneg.read().split(', ')
  for i,word in enumerate(negfwords):
    negfwords[i] = preprocess(word)
negfwords = [j for sub in negfwords for j in sub]
negfwords = list(set(negfwords))
with open('schoolneg_reply.txt') as schoolnegrep:
  schoolneg = schoolnegrep.read().split(', ')
with open('schoolpos_reply.txt') as schoolposrep:
  schoolpos = schoolposrep.read().split(', ')
with open('famneg_reply.txt') as famnegrep:
  famneg = famnegrep.read().split(', ')
with open('fampos_reply.txt') as famposrep:
  fampos = famposrep.read().split(', ')
with open('Relationship_words.txt') as relword:
  relwords = [word for word in relword.read().split('\n') if word != '']
relwords = [preprocess(word) for word in relwords]
relwords = [word for sub in relwords for word in sub]
relwords = list(set(relwords))
with open('Relationship_posreply.txt') as relq:
  relpos = [sen for sen in relq.read().split('\n') if sen != '']
with open('Relationship_negreply.txt') as reln:
  relneg = [sen for sen in reln.read().split('\n') if sen != '']
with open('depression_words.txt') as deword:
  depwords = [preprocess(word) for word in deword.read().split('\n') if word != '']
depwords = list(set([word for sub in depwords for word in sub]))
with open('depression_posreply.txt') as derep:
  depreply =[sen for sen in derep.read().split('\n') if sen != '']
with open('shame_words.txt') as sword:
  shwords = [preprocess(word) for word in sword.read().split(', ') if word != '']
shwords = list(set([word for sub in shwords for word in sub]))
with open('shamerep.txt') as sre:
  shrep = [sen for sen in sre.read().split('\n') if sen != '']
with open('neg_replies.txt') as neg:
  negrep = [sen for sen in neg.read().split('\n') if sen != '']
othermap = {}
for word in schoolwords:
  othermap[word] = 'School'
for word in familywords:
  othermap[word] = 'Family'
for word in negfwords:
  othermap[word] = 'NEG FEELING'
for word in posfwords:
  othermap[word] = 'POS FEELING'
for word in relwords:
  othermap[word] = 'RELATIONSHIP'
for word in depwords:
  othermap[word] = 'DEPRESSION'
for word in shwords:
  othermap[word] = 'SHAME'

In [26]:
dataset = pd.read_csv('20200325_counsel_chat.csv')
questions = []
answers = []
for i in range(len(dataset)):
  question = dataset['questionTitle'].iloc[i]
  if question not in questions:
    questions.append(question)
    answers.append(dataset['answerText'].iloc[i])

qamap = {}
for i,question in enumerate(questions):
  q = tuple(preprocess(question))
  a = answers[i]
  qamap[q] = a

In [52]:
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
from nltk import word_tokenize
from collections import Counter
import re
def formreply(line,emotion):
  question = line
  q12 = question
  re.sub('\?',' ',question)
  question = preprocess(question)
  counterA = Counter(question)
  max_sim = 0
  for q in qamap.keys():
    ql = list(q)
    counterB = Counter(ql)
    sim = cosine_sim(counterA,counterB)
    count = 0
    for key1 in counterA.keys():
        if key1 in counterB.keys():
          count += 1
    if count >= 1:
      if sim > max_sim:
        max_sim = sim
        key = q
  flag = 1
  if max_sim > 1.75:
    if(max_sim > 2.4 and count == 1) or (max_sim > 1.8 and count >= 2):
      print(question)
      print(key)
      print(max_sim)
      print(qamap[key])
      flag = 0
  if flag == 1:
    out = []
    for word in question:
      if word in othermap.keys():
        out.append(othermap[word])
      else:
        out.append('Unknown')
    counterTopic = Counter(out)
    #print(counterTopic)
    if emotion == 'joy':
      polarity = 'pos'
    elif emotion == 'neutral':
      polarity = 'neutral'
    else:
      polarity = 'neg'
    del counterTopic['POS FEELING']
    del counterTopic['NEG FEELING']
    counterTopic['Unknown'] = 0
    #print(counterTopic)
    maxCount = 0
    for key,item in counterTopic.items():
      if counterTopic[key] >= maxCount:
        maxCount = item
        topic = key
    #print(question)
    print('You are talking about topic : ' + topic)
    print('Polarity : ' + polarity)
    #print(q12)
    return classify(topic.upper(),polarity,q12)


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


In [54]:
def classify(topic,polarity,q1):
  if topic == 'SCHOOL':
    if polarity == 'pos':
      return formreply1(schoolpos,q1,1)
    else:
      return formreply1(schoolneg,q1,1)
  elif topic == 'FAMILY':
    if polarity == 'pos':
      return formreply1(fampos,q1,1)
    else:
      return formreply1(famneg,q1,1)
  elif topic == 'RELATIONSHIP':
    if polarity == 'pos':
      return formreply1(relpos,q1,1)
    else:
      return formreply1(relneg,q1,1)
  elif topic == 'DEPRESSION':
    return formreply1(depreply,q1,1)
  elif topic == 'SHAME':
    return formreply1(shrep,q1,1)
  elif topic == 'UNKNOWN':
    if polarity == 'pos':
      ind = random.randint(0,len(affirm_ans)-1)
      return affirm_ans[ind]
    else:
      return formreply1(negrep,q1,1)

In [55]:
import random
def formreply1(category,question,num):
  proc = []
  for line in category:
    proc.append(preprocess(line))
  max = 0
  reply = ''
  for i,line in enumerate(proc):
    question1 = question.split()
    countera = Counter(line)
    counterb = Counter(question1)
    sim = cosine_sim(countera,counterb)
    count = 0
    for key in counterb.keys():
      if key in countera.keys():
        count += 1
    if count >= 1:
      if sim > max:
        max = sim
        reply = category[i]
  if reply == '':
    ind = random.randint(0,len(category)-1)
    reply = category[ind]
  return reply

In [56]:
import math
def cosine_sim(c1,c2):
  terms = set(c1).union(c2)
  dotprod = sum(c1.get(k,0) * c2.get(k,0) for k in terms)
  sqa = math.sqrt(sum(c1.get(k,0)**2 for k in terms))
  sqb = math.sqrt(sum(c2.get(k,0)**2 for k in terms))
  if sqa != 0 and sqb != 0:
    return dotprod/sqa*sqb
  else:
    return 0

In [59]:
import re
import random
last_6_emotions = []
df = []
while True:
  line = input("You: ")
  l1 = line
  if line == "endl":
    break
  emotion = preproc(line)
  if emotion == -100:
    continue
  print("Emotion of above sentence : " + emotion)
  if len(last_6_emotions) != 6:
    last_6_emotions.append(emotion)
  else:
    ag_emotion = aggregate()
    change = get_emotion_details(ag_emotion)
    print("Overall emotion over 6 inputs : " + str(ag_emotion))
    if change != 0:
      print("Change in emotion percentage over last two conversations : " + str(change))
    last_6_emotions = []
    last_6_emotions.append(emotion)
  reply = ""
  reply = formreply(l1,emotion)
  print('Chatbot : ' + reply)
  #aggregate = find_overall()
  #print("Aggregate emotion : " + aggregate)

You: Sometimes I wonder whether life is worth living for
['wonder', 'life', 'worth', 'live']
Emotion of above sentence : fear
You are talking about topic : Unknown
Polarity : neg
Chatbot : Life is the way it is! You just need the energy and the confidence to work through it.
You: No one will miss me if I die
['miss', 'die']
Emotion of above sentence : guilt
You are talking about topic : School
Polarity : neg
Chatbot : Talk Talk Talk... Thats the only advice I can give you.
You: Life sucks
['life', 'suck']
Emotion of above sentence : joy
You are talking about topic : Unknown
Polarity : pos
Chatbot : Thank you for telling me this!
You: I feel so anxious sometimes that I want to just scream
['feel', 'anxious', 'want', 'scream']
Emotion of above sentence : disgust
You are talking about topic : Unknown
Polarity : neg
Chatbot : I feel ya!
You: Will life get better?
Hmm.. I need to think about it.
You: will life ever get better
['life', 'better']
Emotion of above sentence : joy
You are talkin

In [ ]:
dataset = pd.read_csv('100 questions to ask a bot.csv')

In [ ]:
Common_questions = dataset.iloc[:,0].values


In [ ]:
New_common_q = []

In [ ]:
for sen in Common_questions:
  line = re.sub('  \n',' ',sen)
  line = re.sub('[^a-zA-Z]',' ',line)
  line = line.lower()
  line = line.split()
  line = [ps.stem(word) for word in line]
  line = ' '.join(line)
  new_train = elmo_vectors([line])
  New_common_q.append(new_train)

In [ ]:
pickle_out = open("cq.pickle","wb")
pickle.dump(New_common_q,pickle_out)
pickle_out.close()

In [ ]:
from scipy.spatial import distance
line = input()
line = re.sub('  \n',' ',line)
line = re.sub('[^a-zA-Z]',' ',line)
line = line.lower()
line = line.split()
line = [ps.stem(word) for word in line]
line = ' '.join(line)
new_train = elmo_vectors([line])
new_train = np.reshape(new_train,(1024,1))
distances = distance.cdist(new_train, New_common_q, "cosine")[0]
min_index = np.argmin(distances)
min_distance = distances[min_index]
max_sim= 1 - min_distance
print("Max Similarity : " + str(max_sim))
print("Question : " + Common_questions[min_ind])
print("Reply : " + Common_answers[min_ind])

In [ ]:
from textblob import TextBlob

In [ ]:
noun_list = []

In [ ]:
Questions = Common_questions.tolist()

In [ ]:
pos_pop = []

In [ ]:
for i in range(0,len(Questions)):
  blob = TextBlob(Questions[i])
  noun = blob.noun_phrases
  if len(noun) == 0:
    Answers[i] = ''
    continue
  noun_list.append(noun)

In [ ]:
noun_answers = []
for i in range(0,len(Answers)):
  blob = TextBlob(Answers[i])
  noun = blob.noun_phrases
  noun_answers.append(noun)
noun_ans = []
for i in range(0,len(Answers)):
  sen = ' '.join(noun_answers[i])
  noun_ans.append(sen)

In [ ]:
noun_ans

In [ ]:
len(Answers)

32

In [ ]:
na = {}
for i in range(0,len(Answers)):
  na[noun_ans[i]] = Answers[i]


In [ ]:
del na['']

In [ ]:
na

In [ ]:
import json
json = json.dumps(na)
f = open("canswers.json","w")
f.write(json)
f.close()

In [ ]:
len(pos_pop)

22

In [ ]:
for num in pos_pop:
  Answers.pop(num)

In [ ]:
Common_answers = dataset.iloc[:,1].values
Answers = Common_answers.tolist()

In [ ]:
Answers = [i for i in Answers if i]

In [ ]:
len(Answers)

In [ ]:
ds = {}

In [ ]:
for i in range(0,len(noun_list)):
  ds1[nq[i]] = Answers[i]

In [ ]:
for id, key in enumerate(ds1):
  ds1[key] = ds1[key].lower()

In [ ]:
ds

In [ ]:
questions = []
for i in range(0,len(noun_list)):
  sen = ' '.join(noun_list[i])
  questions.append(sen)

In [ ]:
import re
nq = []
for i in range(0,len(questions)):
  if "who" in questions[i]:
    question = questions[i].replace("who ","")
    nq.append(question)
  else:
    nq.append(questions[i])

In [ ]:
nq = nq.remove("who")

In [ ]:
nq

In [ ]:
import nltk
nltk.download('brown')
nltk.download('punkt')